---

# handlers file for install_apache
- name: restart_apache
  service:
    name: apache2
    state: restarted
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'


- name: restart_httpd
  service:
    name: httpd
    state: restarted
  when: ansible_distribution == "CentOS"

- name: restart_ufw
  service:
    name: ufw
    state: restarted
